apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cjya8muzi-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cjya8muzi-nodejs 
  name: cjya8muzi-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cjya8muzi-nodejs 
